name: Cut Release

on:
  workflow_dispatch:
    inputs:
      kind:
        required: true
        type: choice
        description: The kind of release to cut
        options:
        - beta
        - patch
        - minor
        - major

      specific_version:
        required: false
        description: "Optional - Specific Version (eg: 0.0.1-beta.420)"
        type: string

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true

jobs:
  work:
    runs-on: ubuntu-24.04 # need node 20+
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install NPM Dependencies
        shell: bash
        run: cd cli && npm install

      - name: Cut Release
        env:
          GH_APP_ID: '229901'
          GH_APP_INSTALLATION_ID: '36921303'
          GH_APP_PRIVATE_KEY: ${{ secrets.KONG_APP_KEY_V2 }}
        run: |
          ./run bump-version --${{ inputs.kind }} ${{ inputs.specific_version }}
          ./run gh-create-release "${{ github.event.repository.name }}"
          ./run gh-push-php
          ./run gh-create-release statsig-core-php

